#versão .properties
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
server:
  port: 8081
cors:
  originPatterns: http://localhost:3000,http://localhost:8081
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:33306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
spring-doc:
  pathsToMatch:
    - /auth/**
    - /v1/**
  swagger-ui:
    use-root-path: true